pkg/network/utils.go

This commit add the ability to skip the virtual function interfaces from the list of supported ptp interfaces

Skip SRIOV virtual functions interfaces

---

pkg/network/utils.go

This small commit just changes the exec.command("readlink) to the os.ReadLink function.

Use os.readlink instead of exec.command

---

Dockerfile
Dockerfile.rhel7
cmd/main.go
hack/build.sh
pkg/config/config.go
pkg/daemon/daemon.go
pkg/daemon/metrics.go
pkg/daemon/ptpdev.go

Create a loop for the device discovery.
This PR also changes the Dockerfiles to use the vendor folder on the build and not fetch the modules.
Related to the follow error:
```
PTP capable NICs: [eno1 eno2]
E0418 22:40:28.559220    4744 main.go:84] failed to get NodePtpDevice CR for node cnfd1-worker-0.fci1.kni.lab.eng.bos.redhat.com: Get https://172.30.0.1:443/apis/ptp.openshift.io/v1/namespac
es/openshift-ptp/nodeptpdevices/cnfd1-worker-0.fci1.kni.lab.eng.bos.redhat.com: dial tcp 172.30.0.1:443: i/o timeout
I0418 22:40:28.587016    4744 ptpdev.go:15] PTP capable NICs: [eno1 eno2]
E0418 22:40:28.587075    4744 main.go:93] failed to update Node PTP device CR: resource name may not be empty
I0418 22:40:58.589483    4744 main.go:122] ticker pull
```

Run device discovery in a loop

---

Dockerfile.rhel7

Updating linuxptp-daemon builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/linuxptp-daemon.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating linuxptp-daemon builder & base images to be consistent with ART

---

pkg/daemon/metrics.go

This commit add a check for the number of fields
in the metrics parser functions

Bug 1892467: Make the metrics parser more robust

---

pkg/daemon/ptpdev.go

In CI there was a flake that added a VF to the list of devices in the NodePtpDevice CRD.
The daemon always append to the list of devices in the node status instead of replacing, so
if there is a race in the detection of a vf this is never reconciled.

Bug 1892724: Always replace the list of devices instead of appending.

---

pkg/daemon/config.go

This commit this a crash when there is no policy before the upgrade
```
I1122 12:36:17.903050 1546704 ptpdev.go:21] PTP capable NICs: [eno1 eno2]
I1122 12:36:47.820480 1546704 main.go:98] ticker pull
I1122 12:36:47.820680 1546704 config.go:56] load profiles using old method
I1122 12:36:47.820699 1546704 daemon.go:110] in applyNodePTPProfiles
I1122 12:36:47.820703 1546704 daemon.go:132] updating NodePTPProfiles to:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1198e56]
goroutine 122 [running]:
github.com/openshift/linuxptp-daemon/pkg/daemon.(*Daemon).addProfileConfig(0xc0002f8080, 0xc000042180, 0x17, 0xc00064feb0)
/go/src/github.com/openshift/linuxptp-daemon/pkg/daemon/daemon.go:210 +0x146 …
```

Fix crash on update if no policy exist

---

pkg/daemon/metrics.go

This commit fix the debug logs level for the ptp4l.
```
ptp4l[76012.431]: [ens5f0] config item (null).free_running is 0
ptp4l[76012.431]: [ens5f0] config item (null).freq_est_interval is 1
ptp4l[76012.431]: [ens5f0] config item (null).gmCapable is 1
ptp4l[76012.432]: [ens5f0] config item (null).kernel_leap is 1
ptp4l[76012.432]: [ens5f0] config item (null).utc_offset is 37
E1124 15:48:57.058232 3935542 metrics.go:157] ptp4l failed to parse output offset is 37: unexpected number of fields
ptp4l[76012.432]: [ens5f0] config item (null).timeSource is 160
ptp4l[76012.432]: [ens5f0] config item (null).pi_proportional_const is 0.000000
ptp4l[76012.432]: [ens5f0] config item (null).pi_integral_const is 0.000000
ptp4l[76012.432]: [ens5f0] config item (null).pi_proportional_scale is 0.000000 …
```

Bug 1901200: Fix metrics expose on debug level

---

pkg/daemon/metrics.go

This commit fix the debug logs level for the ptp4l.
```
ptp4l[76012.431]: [ens5f0] config item (null).free_running is 0
ptp4l[76012.431]: [ens5f0] config item (null).freq_est_interval is 1
ptp4l[76012.431]: [ens5f0] config item (null).gmCapable is 1
ptp4l[76012.432]: [ens5f0] config item (null).kernel_leap is 1
ptp4l[76012.432]: [ens5f0] config item (null).utc_offset is 37
E1124 15:48:57.058232 3935542 metrics.go:157] ptp4l failed to parse output offset is 37: unexpected number of fields
ptp4l[76012.432]: [ens5f0] config item (null).timeSource is 160
ptp4l[76012.432]: [ens5f0] config item (null).pi_proportional_const is 0.000000
ptp4l[76012.432]: [ens5f0] config item (null).pi_integral_const is 0.000000
ptp4l[76012.432]: [ens5f0] config item (null).pi_proportional_scale is 0.000000 …
```

Bug 1901877: Fix metrics expose on debug level

---

pkg/daemon/daemon.go

Short fix for https://bugzilla.redhat.com/show_bug.cgi?id=1914303
It is helpful to get all ptp4l and phc2sys log output (stdout and stderr) for troubleshooting purpose.

Bug 1914303: Add cmd stderr redirection to os.Stderr

---

pkg/network/utils.go

This commit fix the linuxptp to work with the latest ethtool version on rhcos
ethtool output on old version:
```
ethtool.x86_64                     2:5.4-1.fc30                     @updates
Time stamping parameters for eno1:
Capabilities:
hardware-transmit     (SOF_TIMESTAMPING_TX_HARDWARE)
software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
hardware-receive      (SOF_TIMESTAMPING_RX_HARDWARE)
software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
hardware-raw-clock    (SOF_TIMESTAMPING_RAW_HARDWARE)
PTP Hardware Clock: 0
Hardware Transmit Timestamp Modes:
off                   (HWTSTAMP_TX_OFF)
on                    (HWTSTAMP_TX_ON)
Hardware Receive Filter Modes:
none                  (HWTSTAMP_FILTER_NONE)
ptpv1-l4-event …
```

Bug 1955196: ethtool output change

---

cmd/main.go
pkg/daemon/daemon.go
pkg/daemon/metrics.go

This is for Openshift 4.9, moving metrics to the sidecar PTP plugin.
PTPLinux daemon will write cmd output to Unix socket which will be mounted by the deployment and shared between the sidecar and the ptp Linux daemon.
The PTP plugin will consume cmd out from the socket and create Prometheus metrics.
Do I need to keep metrics on Linux PTP Daemon set for backport purposes?

enable propagating metrics from ptp Linux daemon to sidecar via socket

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go

This PR fixes Prometheus  metrics for multi interface and single interface case.
Last PR added config filename  to the log instead of interface and and then extract metrics method signature was changed to send   list of interfaces to parse and match the port id from the role to determine the interface role.
This PR uses those changes to update Prometheus metrics , by adding new metrics and updating existing now.
Introduced following metrics 
openshift_ptp_clock_state{iface="master",node="cnfde7.ptp.lab.eng.bos.redhat.com",process="ptp4l"}
openshift_ptp_ptp_interface_role{iface="ens5f1",node="cnfde7.ptp.lab.eng.bos.redhat.com",process="ptp4l"} 1
openshift_ptp_delay_from_system{iface="ens7f1",node="cnfde7.ptp.lab.eng.bos.redhat.com",process="phc2sys"} 2720
Single interface Metrics 
``` …
```

Bug 1993854: add metrics for multi interface

---

pkg/daemon/metrics.go

with summary_interval=0 in ptp config, the ptp4l log will produce rms log without interface name , this  was causing parsing error because parsing logic is based on position of the fields in the logs and expected to have interface name.
This PR takes care of both  conditions with interface and without interface name in the ptp4l rms logs

Bug 1999185:Fixed parsing error

---

pkg/daemon/metrics.go

log out put 
```
ptp4l.0.config master offset -2162130      s2    freq +22451884  delay 374976
ptp4l.0.config eno1   sys    offset        13     s2   freq      +6010 delay    468
```
Offset generally seen at index 2, if it is at index 3 then move it to index 2, but for some setup log adds sys field which throws an parsing error .
This PR makes sure the 2nd field is always offset. If it is found  at field 3 then  log an error

Bug 1999185: with master summary_interval phc2sys adds sys to the log

---

pkg/daemon/ptpdev.go

runDeviceStatusUpdate was called every minute to check PTP capabilities of the nic and update the nodePtpDevice CR status.
This was causing CPU usage to spike every minute.
The change will remove the loop and call it only once and update the CR with the status as shown below.
```
status:
devices:
- name: eno1
- name: eno2
- name: ens5f0
- name: ens5f1
- name: ens7f0
- name: ens7f1
```

Bug 2024731:Remove ethtool status check loop

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go

The PR removes all events for master ports.
Only shows events for CLOCK_REALTIME and master offset for PHC clock 
example:
following logs will only calculate offset events for master offset and CLOCK_REALTIME only  and ignore ens7f0 in all metrics and events
Log output 
```
phc2sys[619569.614]: [ptp4l.0.config] CLOCK_REALTIME rms 1525 max 1525 freq -79792 +/-   0 delay   405 +/-   0
phc2sys[619569.614]: [ptp4l.0.config] ens7f0 rms 3936 max 3936 freq  -6428 +/-   0 delay  3040 +/-   0
ptp4l[619569.636]: [ptp4l.0.config] master offset       -571 s2 freq   -4212 path delay        92
```
Metrics
```
openshift_ptp_max_offset_ns{from="master",iface="ens7fx",node="cnfde7.ptp.lab.eng.bos.redhat.com",process="ptp4l"} 5 …
```

Bug 2047308 : Remove metrics and events for master port offsets

---

pkg/daemon/daemon.go

while parsing value for gm.Clockclass, the logic was parsing every string from findSubstring slice
The fix avoids false error and parses only the matched value from the regex

Bug 2090809: clock class parsing error fix

---

pkg/daemon/config.go
pkg/daemon/daemon.go

Fix an issue introduced by iface ordering change, where Interfaces only
passed in through interface field in ptpconfig API would not be added to
ptp4l config file.
Also add support for commenting out lines in ptpconfig.
Also remove ' ' at start of every line in generated config file.

OCPBUGS-560: Fix passing interface in ptpconfig through API field

---

Dockerfile

Fedora is significantly different than ocp builder image, and so testing in fedora image may not be valid for standard production image. Switch to using ocp builder image in Dockerfile.

Stop using fedora in non-rhel Dockerfile

---

pkg/daemon/metrics.go

remove noise from the log
glog.Errorf("%s failed to parse output %s: unexpected number of fields", processName, output)

BUG OCPBUGS-2073: remove logging error for unrelated parsing of log string

---

pkg/daemon/metrics.go

remove noise from the logs
glog.Errorf("%s failed to parse output %s: unexpected number of fields", processName, output)

[release-4.11] Bug OCPBUGS-2074: Remove noise from the log when parsing ptp4l logs

---

pkg/daemon/metrics.go

remove printing this
glog.Errorf("%s failed to parse output %s: unexpected number of fields", processName, output)

 [release-4.10]  Bug OCPBUGS-791: remove ptp4l parsing noise in the log

---

Dockerfile
Dockerfile.rhel7

Workaround for missing leap-seconds.list.  Ideally this would be fixed in RHEL, but workaround for now.

Add leap-seconds.list to Dockerfile

---

cmd/main.go

This PR adds  first part of nodename as label to daemon pod. Which is needed for http  events service to work on multi node.
http is not supported  in 4.13 but need to back port to 4.12
Need to back port  https://github.com/openshift/ptp-operator/pull/282 to support multi node.

OCPBUGS-8249: add support for multinode service for http moving from 4.13 to 4.12

---

pkg/daemon/daemon.go

Multiple processes (e.g. ptp4l and phc2sys) can use same ptp4lSocket, so wait to close until none are still using it.
/hold until testing is done

Bug OCPBUGS-8112: Delay closing ptp4lSocket

---

addons/generic/generic.go
addons/intel/e810.go
cmd/main.go
pkg/daemon/daemon.go
pkg/daemon/plugin.go
pkg/daemon/ptpdev.go
pkg/plugin/plugin.go

/hold
initial example for testing purposes.  Currently populates with irrelevant data.  Need to integrate with plugin framework before this merges.

OCPBUGS-13875: Add initial hwconfig population

---

extra/leap-seconds.list

BUG OCPBUGS-15584: leap-seconds.list file included as part of linuxptp-daemon container expired on June 28, 2023

---

Dockerfile.rhel7

from #[153](https://github.com/openshift/linuxptp-daemon/pull/153) to enable downstream builds

revert changes to Dockerfile.rhel7

---

addons/intel/e810.go
pkg/daemon/daemon.go
pkg/dpll/dpll.go

Allow customizing DPLL settings through e810 plugin
spec:
profile:
- name: grandmaster
plugins:
e810:
settings:
LocalMaxHoldoverOffSet: 1500
LocalHoldoverTimeout: 14400
MaxInSpecOffset: 100

OCPBUGS-17094: Allow customizing DPLL settings through e810 plugin

---

go.mod
go.sum
pkg/daemon/daemon.go
pkg/daemon/gpsd.go
pkg/daemon/metrics.go
pkg/dpll/dpll.go
pkg/event/event.go
pkg/pmc/pmc.go
pkg/ublox/ublox.go
vendor/github.com/aneeshkp/go-gpsd/.gitignore
vendor/github.com/aneeshkp/go-gpsd/LICENSE
vendor/github.com/aneeshkp/go-gpsd/README.md
vendor/github.com/aneeshkp/go-gpsd/gpsd.go
vendor/modules.txt

This PR uses the direct call to gpsd for monitoring the GNSS state.
Current monitoring doesn't have GNSS offset. 
Once it is available then the offset will be reported accurately.

OCPBUGS-16220: Replace Ublox with direct call to default gpsd  for monitoring and  reduce CPU usage 

---

pkg/dpll/dpll.go
pkg/dpll/dpll_test.go
pkg/event/event.go
pkg/event/event_test.go
pkg/event/pubsub.go

Add subscriber pattern
This fixes issue with getting state of unrelated process without depending on channels

OCPBUGS-17470: GNSS state change is not captured by DPLL Netlink event listener

---

pkg/dpll-netlink/dpll-uapi.go
pkg/dpll/dpll.go

This commit fixes a mistake in netlink dpll notification parsing. The parsing should be done by type and not by id
/cc @aneeshkp @jzding  @josephdrichard

OCPBUGS-17454: parse DPLL replies by type

---

addons/intel/e810.go
pkg/daemon/daemon.go
pkg/dpll/dpll.go

This commit changes the way T-GM clock id is attained
to be consistent with what Intel ice driver does.
/cc @aneeshkp @jzding @josephdrichard

OCPBUGS-17586: Get DPLL clock ID from card DSN

---

pkg/config/config.go
pkg/daemon/daemon.go
pkg/daemon/gpsd.go
pkg/dpll/dpll.go
pkg/dpll/dpll_test.go
pkg/event/event.go
pkg/event/pubsub.go
pkg/event/stats.go
pkg/protocol/type.go

Fix race conditions between monitoring process and event handler.- Event handler need to wait for side car socket to be available before process can be initiated. 
Now dpll  and gpsd Monitoring are called via event handler.
The dpll monitoring and gpsd monitoring calls will be registered with event-handler .
Once event-handler is available to serve, the Event-handler will run monitors

OCPBUGS-17971: DPLL netlink API should retry sending events to event handler when send fails

---

pkg/config/config.go
pkg/daemon/daemon.go
pkg/daemon/gpsd.go
pkg/dpll/dpll.go
pkg/event/event.go
pkg/event/event_test.go
pkg/event/stats.go
pkg/protocol/type.go

Defining HOLDOVER/LOCKED and FREERUN state from DPLL 
With Lost Source, IN Spec, and Out of Spec state transitions.
When GNSS is Lost, if the DPLL is in HOLDover and inSpec then do not set it to FREERUN, Instead, GM should be in Holdover state

OCPBUGS-17526: clock class is not set to 140 when DPLL is lost source and out of spec - from holdover

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go

concurrent map read write fix , which was found occasionally hitting this issue

OCPBUGS-20413: [release 4-12] concurrent map reading master offset map in linuxptpdaemon

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go
pkg/dpll/dpll_test.go
pkg/event/event.go
pkg/event/event_test.go

OCPBUGS-24043: nmea_status and clock_class metrics missing in 4.14 linuxptpdaemon

---

pkg/daemon/daemon.go

Fixup issue preventing ubxtool commands from being run by e810 plugin when there are multiple node profiles configured.

OCPBUGS-24010: fixup node profile access from plugin

---

pkg/daemon/daemon_test.go
pkg/daemon/metrics.go

-     update clock state to FREERUN when the slave port is down
-     update help text for openshift_ptp_clock_class

OCPBUGS-29024: update clock state to FREERUN when the slave port is down

---

pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/metrics.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
vendor/modules.txt

Update clock state to FREERUN when the slave port is down.
Update help text for openshift_ptp_clock_class.
Add unit tests for metrics and events.

[release-4.15] OCPBUGS-29102: update clock state to FREERUN when the slave port is down

---

pkg/dpll/dpll.go
pkg/dpll/dpll_test.go

This fixes a bug introduced in #271 leading to dpll phase offset freezing during trasitions to holdover and freerun states, where DPLL netlink indications from the driver stop. It also fixes the problem of not in-spec report on DPLL that has PPS as a source
/cc @aneeshkp @josephdrichard @jzding

OCPBUGS-30856: Fix DPLL offset on holdover and freerun

---

addons/intel/README.md
addons/intel/e810.go
pkg/daemon/daemon.go
pkg/dpll-netlink/dpll-uapi.go
pkg/dpll-netlink/dpll.go
pkg/dpll/dpll.go
pkg/dpll/dpll_test.go

This is a manual cherry-pick from three commits: #271, #276 and #279.
Add DPLL pin notification parser and handle pin notifications. Distinguish between pin notifications and device notifications. Update DPLL phase offset if included for the pin belonging to the DPLL instance.

OCPBUGS-30810: add DPLL phase offset

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go

Enable log severity via message_tag the log severity will be suffixed to message tag and available in container logs 
example : ptp4l[2464681.628]: [ptp4l.1.config:7] master offset         -4 s2 freq  -26835 path delay       525
ptp4l[2485169.871]: [ptp4l.0.config:3] increasing tx_timestamp_timeout or increasing kworker priority may correct this issue, but a driver bug likely causes it
ptp4l[2485169.871]: [ptp4l.0.config:3] port 1 (ens2f0): send delay request failed
ptp4l[2485169.871]: [ptp4l.0.config:5] port 1 (ens2f0): SLAVE to FAULTY on FAULT_DETECTED (FT_UNSPECIFIED)
ptp4l[2485169.880]: [ptp4l.1.config:6] master offset         -1 s2 freq  -26803 path
3=Error ;5=Warning 6=Debug

OCPBUGS-31422: PTP container logs lack severity information

---

pkg/daemon/daemon.go

This is followup fix for https://github.com/openshift/linuxptp-daemon/pull/288
Fix issue with reading log from linuxptp with dev/ptp; this bug was preventing event framework from identifying interface name when linuxptp was sending ts2phc offset with /dev/ptpx  for interface name

OCPBUGS-31370: fix ts2phc clock id from offset output and replace it with interfacename -Followup for event framework

---

pkg/daemon/config.go
pkg/daemon/gpsd.go

The process restart was failing because the gpsd service wasn't shutting down properly (ending gracefully). This caused the cmdStop function to stall because gpsd was essentially hijacking it.
This Pull Request Fixes:
Ensures gpsd terminates gracefully before the process restart, preventing it from blocking the cmdStop function.

OCPBUGS-31602: interfaces for deleted ptpconfig profiles still appear in metrics- process are not getting terminated 

---

addons/intel/README.md
addons/intel/e810.go
pkg/daemon/daemon.go
pkg/daemon/gpsd.go
pkg/daemon/gpspipe.go
pkg/dpll-netlink/dpll-uapi.go
pkg/dpll-netlink/dpll.go
pkg/dpll/dpll.go
pkg/dpll/dpll_test.go
pkg/event/event.go
pkg/event/pubsub.go
pkg/event/stats.go
pkg/ublox/ublox.go

Merges  following fixes
OCPBUGS-30982  https://github.com/openshift/linuxptp-daemon/pull/284
OCPBUGS-31601 https://github.com/openshift/linuxptp-daemon/pull/293
OCPBUGS-32140: https://github.com/openshift/linuxptp-daemon/pull/299
OCPBUGS-31698:  interfaces for deleted ptpconfig profiles still appear in metrics- process are not getting terminated

[release-4.14] OCPBUGS-32441: Ublox Reboot fix and reading  Offset from Ublox and DPLL

---

pkg/daemon/daemon.go

Trim space of phc2sys and ptp4l config options.
If ptpConfig Opts are set with spaced empty string , then the daemon considers as value and tries to run the process for empty  spaced string

OCPBUGS-33524: PTP Boundary HA configuration cannot handle spaced empty Phc2SysOpts and ptp4lOpts with

---

pkg/daemon/daemon.go

Reverts openshift/linuxptp-daemon#304
GM configuration is not applying correctly when setting ts2phc options to " " empty spaced string

OCPBUGS-34198: Revert "OCPBUGS-33524: PTP Boundary HA configuration cannot handle spaced empty Phc2SysOpts and ptp4lOpts with"

---

Dockerfile
go.mod
pkg/daemon/daemon.go
pkg/daemon/metrics.go

This update port back some fixes around metrics cleanup and refactor from the following commits, except HA changes.
https://github.com/openshift/linuxptp-daemon/pull/275
https://github.com/openshift/linuxptp-daemon/pull/277
https://github.com/openshift/linuxptp-daemon/pull/280
Use sort.Slice() instead of slices.SortFunc() since the latter is not available in golang 1.20.

[release-4.15] OCPBUGS-32305: fix missing openshift_ptp_process_status metric initial install

---

pkg/leap/leap-file.go

This fixes a bug causing leap file expiration date to be off by 70 years and update date to be outdated

OCPBUGS-34804: fix leap file expiration and update times

---

Dockerfile

This bumps golang to 1.22, so CI will pass

bump golang to 1.22

---

extra/leap-seconds.list

updated leap file to expire on dec 28th
https://data.iana.org/time-zones/data/leap-seconds.list

[release-4.15] OCPBUGS-35872: leap-seconds.list file included as part of linuxptp-daemon container expired on June 28, 2024

---

Dockerfile

Update dockerfile to use linuxptp 4.2 and synce4l rpm 
This is temporary fix until  base container image is updated to 9.4

Update dockerfile to use 4.17 base image

---

cmd/main.go
go.mod
pkg/daemon/daemon.go
pkg/daemon/daemon_internal_test.go
pkg/daemon/gpsd.go
pkg/event/event.go
pkg/event/event_test.go
pkg/leap/leap-file.go
pkg/leap/leap-file_test.go

This PR fixes a bug where the daemon wrote uninitialized values to the time properties dataset, which led to corrupting the ptp time scale, current UTC offset and other dataset properties. The fix is done by always initializing the time properties according to the current UTC offset and a predefined set of flags. Leap manager was changed to provide current UTC offset to external packages.

OCPBUGS-37042: prevent writing uninitialized TimePropertiesDS

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go
pkg/event/event.go

The ts2phc process termination only triggers FREERUN and doesn't recover back. This PR fixes this issue by sending the process status to the GM Event Decision Engine, which will mark T-GM as FREERUN. The event framework will use the PROCESS_DOWN indication to produce accurate events.

OCPBUGS-35587: T-GM - ts2phc process restart doesn't update PTP syncState when the process recovered

---

pkg/daemon/daemon.go
pkg/daemon/daemon_internal_test.go
pkg/leap/leap-file.go
pkg/leap/leap-file_test.go

this commit adds leap event handling that includes following:
1. Determine that current time is within -12h...1m from the leap
2. Send PMC command (once) to indicate leap61 or leap 59 to the downstream architecture and
3. Handle ts2phc time ambiguity

OCPBUGS-36201: implement leap event handling

---

pkg/leap/leap-file.go

This commit fixes leap second pmc command time window. Before the fix, pmc command is sent in a time window from -12h to +60s relatively to the leap event. The correct time window is -12h to -60s

CNF12625: fix Leap second PMC command time window

---

cmd/main.go
pkg/daemon/daemon.go
pkg/daemon/gpsd.go
pkg/event/event.go
pkg/event/event_test.go
pkg/leap/leap-file.go
pkg/leap/leap-file_test.go

This PR fixes a bug where the daemon wrote uninitialized values to the time properties dataset, which led to corrupting the ptp time scale, current UTC offset and other dataset properties. The fix is done by always initializing the time properties according to the current UTC offset and a predefined set of flags. Leap manager was changed to provide current UTC offset to external packages.
This is a manual cherrypick of #335 

[release-4.16] OCPBUGS-37043: prevent writing uninitialized TimePropertiesDS

---

Dockerfile
pkg/daemon/config.go
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/metrics.go
pkg/event/event.go
pkg/synce/synce.go
pkg/synce/synce_test.go

This PR will parse synce4l and create metrics to identify 
1. networkOptions
2. Clock Quality  metrics with indvidual ext-QL and  QL metrics 
3. Synce State metrics 
synce4l[622796.479]: [synce4l.0.config] tx_rebuild_tlv: attached new TLV, QL=0xf on ens7f0",
synce4l[622796.479]: [synce4l.0.config] tx_rebuild_tlv: attached new extended TLV, EXT_QL=0xff on ens7f0
synce4l[627602.540]: [synce4l.0.config]EEC_LOCKED/EEC_LOCKED_HO_ACQ on GNSS of synce1
synce4l[627602.540]: [synce4l.0.config] EEC_HOLDOVER on synce1
synce4l[627602.593]: [synce4l.0.config] tx_rebuild_tlv: attached new TLV, QL=0xf on ens7f0
synce4l[627602.593]: [synce4l.0.config] tx_rebuild_tlv: attached new extended TLV, EXT_QL=0xff on ens7f0
synce4l[627685.138]: [synce4l.0.config] EEC_LOCKED/EEC_LOCKED_HO_ACQ on GNSS of synce1 …

parse  synce logs to create metrics and events 

---

pkg/daemon/config.go
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/synce/synce.go
pkg/synce/synce_test.go

Use 0x3 as default for QL values   and use DNU and DUS for HOLDOVER and FREERUN
which is 0xf for SSM Option1 and 2

Fix SSM code for DNU and DUS for network 1 and 2 

---

cmd/main.go
pkg/daemon/daemon.go
pkg/daemon/gpsd.go
pkg/event/event.go
pkg/event/event_test.go
pkg/leap/leap-file.go
pkg/leap/leap-file_test.go

This PR fixes a bug where the daemon wrote uninitialized values to the time properties dataset, which led to corrupting the ptp time scale, current UTC offset and other dataset properties. The fix is done by always initializing the time properties according to the current UTC offset and a predefined set of flags. Leap manager was changed to provide current UTC offset to external packages.
This is a manual cherry-pick of #341

 	OCPBUGS-37044: [release-4.15] prevent writing uninitialized TimePropertiesDS

---

Dockerfile
pkg/daemon/daemon.go
pkg/daemon/metrics.go
pkg/debug/debug.go
pkg/debug/debug_test.go
pkg/dpll/dpll.go
pkg/event/event.go

Holdover Enabled when GNSS time source  is lost :
The operator will  configure  ts2phcOpts: "--ts2phc.holdover ( timer calculated from DPLL )  --servo_offset_threshold  99999999 --servo_num_offset_values 10" 
The holdover should timeout same time as DPLL , hence we calculate DPLL timer to configure ts2phc holdover timeout 
--ts2phc.holdover : The holdover interval, specified in seconds. 
When the ToD information stops working  (e.g. GNSS receiver lost its fix), `ts2phc` is allowed for the specified interval to continue synchronizing the target clock as long as the servo is in the `SERVO_LOCKED_STABLE` state. 
The servo state needs be enabled by the  `servo_offset_threshold` option. The holdover is not supported with the `-a` option and when `ts2phc.extts_polarity` is set to `both`. The …

OCPBUGS-19838:PTP HW Clock Class after disabling NMEA sentences - Handle T-GM holdover 

---

addons/intel/e810.go

This commit disables SA and SV messages to reduce unnecessare computing load on ts2phc. The amount of these two messages can increase uncontrollably with the number of visible satellites, and they don't provide any useful information for the timing solution.

OCPBUGS-41882: Disable Ublox GNGSA and GNGSV nmea messages

---

addons/intel/e810.go
pkg/daemon/daemon.go
pkg/dpll/dpll.go
pkg/dpll/dpll_test.go
pkg/event/event.go
pkg/event/event_test.go
pkg/event/stats.go

This PR does not address the issue of Clock Class being out of spec for the Time Grandmaster (T-GM) with SyncE. However, it introduces a fix to transition the clock state from HOLDOVER to FREERUN when an out-of-spec state is detected.
Key Changes:
Scenario:
T-GM → GNSS Loss → Clock Class 7 (in Holdover)
Out-of-spec state detected → Transition to FREERUN with Clock Class 248
Note:
SyncE implementation requires Out-of-Spec Holdover, which is not supported in this PR. Further work will be needed to handle this specific SyncE case.
This PR also fixes the updating of clock accuracy for each T-GM state and introduces periodic updates to clock accuracy during the HOLDOVER state based on changes in DPLL offsets.

OCPBUGS-43510: Incorrect Clock Class Transition Behavior in T-GM and PTP Holdover States

---

pkg/daemon/daemon.go
pkg/daemon/daemon_internal_test.go
pkg/daemon/daemon_test.go
pkg/event/event_test.go
pkg/leap/leap-file.go

This fixes the leap window condition check when receiving ts2phc status messages. Any of them should not cause "nmea string lost" event during the leap second clock irregularity.

OCPBUGS-39322: [release-4.18]fix ts2phc leap window check

---

hack/build.sh

Fix fips complaint issue to enable fips support 
Go compliance shim [14] [openshift-4.18][linuxptp-daemon]: non-compliant: eliminated no_openssl

fix fips complaint issue

---

pkg/daemon/daemon.go
pkg/daemon/daemon_internal_test.go
pkg/daemon/daemon_test.go
pkg/event/event_test.go
pkg/leap/leap-file.go

This fixes the leap window condition check when receiving ts2phc status messages. Any of them should not cause "nmea string lost" event during the leap second clock irregularity.

OCPBUGS-39187: [release-4.17] fix ts2phc leap window check

---

go.mod
go.sum
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/event/event_test.go
pkg/leap/leap-file.go
pkg/leap/leap-file_test.go
vendor/github.com/bigkevmcd/go-configparser/LICENSE
vendor/github.com/bigkevmcd/go-configparser/README.md
vendor/github.com/bigkevmcd/go-configparser/TODO.md
vendor/github.com/bigkevmcd/go-configparser/chainmap/chainmap.go
vendor/github.com/bigkevmcd/go-configparser/configparser.go
vendor/github.com/bigkevmcd/go-configparser/interpolation.go
vendor/github.com/bigkevmcd/go-configparser/methods.go
vendor/github.com/bigkevmcd/go-configparser/options.go
vendor/github.com/bigkevmcd/go-configparser/section.go
vendor/modules.txt

This is a manual cherry-pick of #326, #342 and #358

OCPBUGS-39173: [release-4.16] leap event backport

---

pkg/daemon/daemon.go
pkg/dpll/dpll.go
pkg/dpll/dpll_test.go
pkg/event/event.go
pkg/ublox/ublox_test.go

1. Removed NMEA lost updates from metrics and added fault reporting. The ts2phc holdover feature will now manage ts2phc to continue running even when NMEA updates are lost.
2. Added logic to handle Holdover with consideration for whether frequency traceability is available (SyncE enabled) or not. 
Three variables are used in the PTP configuration to manage Holdover: `LocalMaxHoldoverOffset`, `LocalHoldoverTimeout`, and `MaxInSpecOffset`. 
- Holdover timing transitions based on whether frequency traceability is enabled:
- If SyncE is not enabled (frequency traceability is false), a slope calculation is used to determine the time to reach `MaxInSpecOffset`.
- If SyncE is enabled, `LocalHoldoverTimeout` is used to calculate the total holdover duration.
Additionally, updated the logic for …

Enhance Holdover Management and Fault Reporting and holdover in ts2phc/Dpll

---

go.mod
go.sum
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/event/event_test.go
pkg/leap/leap-file.go
pkg/leap/leap-file_test.go
vendor/modules.txt

This is a manual cherry-pick of https://github.com/openshift/linuxptp-daemon/pull/326, https://github.com/openshift/linuxptp-daemon/pull/342 and https://github.com/openshift/linuxptp-daemon/pull/358

OCPBUGS-39175: [release-4.14] Leap event 4.14

---

addons/intel/e810.go
pkg/daemon/gpspipe.go

This commit reduces the number of NMEA messages going to the log and through the `ts2phc` to the essential two message types: GNRMC and GNGGA.
/cc @aneeshkp @jzding @josephdrichard

OCPBUGS-45266: Reduce unwanted NMEA messages

---

pkg/daemon/daemon.go
pkg/dpll/dpll.go
pkg/event/event.go
pkg/event/event_test.go

This covers the case where LocalHoldoverTimeout is smaller than the one defined by MaxInSpecOffset.

OCPBUGS-46370: GM clock class transition to freerun

---

addons/intel/e810.go
pkg/daemon/gpspipe.go

This commit reduces the number of NMEA messages going to the log and
through the `ts2phc` to the essential two message types: GNRMC and
GNGGA.

OCPBUGS-47517: [release-4.16]Reduce unwanted NMEA messages

---

addons/intel/e810.go
pkg/daemon/gpspipe.go

This commit reduces the number of NMEA messages going to the log and
through the `ts2phc` to the essential two message types: GNRMC and
GNGGA.

OCPBUGS-47520: [release-4.15] Reduce unwanted NMEA messages

---

addons/intel/e810.go
pkg/daemon/daemon.go
pkg/daemon/gpspipe.go
pkg/debug/debug.go
pkg/debug/debug_test.go
pkg/dpll/dpll.go
pkg/dpll/dpll_test.go
pkg/event/event.go
pkg/event/event_test.go

**Enhancements to Logging and Clock Class Announcements for T-GM State Management**
This PR introduces structured logging that includes the state tree, providing users with detailed insights into the relationships between all components involved in the Time Grandmaster (T-GM) state decision process. By exposing state transitions and dependencies, this enhancement simplifies troubleshooting and improves the overall observability of T-GM behavior.
Additionally, this PR removes the use of ClockClass 140 (OutOfSpec) and implements the following improvements:  
- Announces **ClockClass 6** during the `LOCKED` state.  
- Announces **ClockClass 7** during the `HOLDOVER` state until one of the following conditions is met:  
- The holdover duration times out.  
- The `inSpecOffset` threshold is …

OCPBUGS-45308: PTP holdover time should be kept for 4 hours 

---

pkg/daemon/metrics.go

This is to add support for the LISTENING port state in metrics. Using a new integer value 5 for backward compatibility (so as to not change previous mappings). 
The LISTENING state is reached when multiple follower ports are receiving PTP frames but only one is selected to become a SLAVE, in slave only mode. The other ports state should be LISTENING (whether they receive PTP frames are received or not).

Add missing LISTENING port states to the list of states reported in metrics

---

pkg/dpll/dpll.go
pkg/dpll/dpll_test.go

This is a manual cherry-pick from #406 
Simplify DPLL eventing logic by decoupling holdover and LHAQ states Remove "locked" DPLL state handling, keeping in Holdover until the LHAQ state reached.
Fix a race condition in tests where event source was not fast enough to be set before the event processing
/cc @aneeshkp @josephdrichard @jzding @nocturnalastro

OCPBUGS-52956: keep in holdover until locked-holdover-acquired

---

pkg/daemon/daemon.go

Wait for socket to be ready before starting the command

OCPBUGS-54680: Add delay in linuxptp-daemon to wait for socket to be ready

---

pkg/dpll/dpll.go
pkg/dpll/dpll_test.go

This is a manual cherrypick of #407 
Simplify DPLL eventing logic by decoupling holdover and LHAQ states 
Remove "locked" DPLL state handling, keeping in Holdover until the LHAQ state reached.
Fix a race condition in tests where event source was not fast enough to be set before the event processing
/assign @aneeshkp 
/cc @josephdrichard @jzding @nocturnalastro

[release-4.17] OCPBUGS-54534: keep in holdover until locked-holdover-acquired

---

pkg/daemon/daemon.go
pkg/event/event.go

For Boundary Clock, the GM clock class is read via the PMC command every few seconds and logged only when there is a change in CLOCK CLASS. This causes the sidecar to miss updates on the clock class value if it restarts or fails to read the first event. Increasing the frequency ensures that the latest clock class is always updated.

OCPBUGS-54960: [4.17] Increasing Clock Class Reporting Frequency #412

---

pkg/dpll/dpll.go
pkg/dpll/dpll_test.go

This is a manual cherry-pick of #413
Simplify DPLL eventing logic by decoupling holdover and LHAQ states Remove "locked" DPLL state handling, keeping in Holdover until the LHAQ state reached.
Fix a race condition in tests where event source was not fast enough to be set before the event processing
/assign @aneeshkp 
/cc @josephdrichard @jzding @nocturnalastro

OCPBUGS-55163: [release-4.16] keep in holdover until locked-holdover-acquired

---

pkg/daemon/daemon.go

Reverts openshift/linuxptp-daemon#416

OCPBUGS-55118: Revert "[release-4.17] OCPBUGS-54693: Add delay in linuxptp-daemon to wait for socket to be ready"

---

pkg/event/event.go
pkg/event/event_test.go

This PR restores a critical logic block that was incorrectly removed in a previous commit. The removed code was responsible for:
missing  logDataValues from dataDetails.logData for log output
if event.WriteToLog && logDataValues != "" {
logOut = append(logOut, logDataValues)
}

[release-4.16] OCPBUGS-55281: update event to fix T-GM regression failure

---

pkg/daemon/daemon.go

The issue was that linuxptp logged severity-level errors to stderr, and the NMEA string timeout was being treated as an error. Our application wasn't capturing stderr, so it was missing those messages. I've now updated it to pipe both stderr and stdout to the same reader.
Now this was corrceted in 4.18 and above, but not found in 4.17 . Log severity was introduced in 4.16

[release-4.16] OCPBUGS-55767: No event when gpsd process restarted

---

pkg/dpll/dpll.go
pkg/dpll/dpll_test.go

Manual cherrypick of #432 
Simplify DPLL eventing logic by decoupling holdover and LHAQ states Remove "locked" DPLL state handling, keeping in Holdover until the LHAQ state reached.
Fix a race condition in tests where event source was not fast enough to be set before the event processing
/assign @aneeshkp

OCPBUGS-55467: [release-4.14] keep in holdover until locked-holdover-acquired

---

go.mod
pkg/daemon/daemon.go
pkg/daemon/metrics.go
pkg/event/event.go
pkg/utils/utils.go
pkg/utils/utils_test.go

Also allows interfaces with the format `<interface name>.<vlan>` 
to be aliased correctly. And uses common function for aliasing
throughout the code.

[release-4.19] OCPBUGS-56423: Fix interface name for summary metrics

---

cmd/main.go
pkg/daemon/metrics.go

The following PR backports the following PRs / commit from 4.19 to 4.18:
- [https://github.com/k8snetworkplumbingwg/linuxptp-daemon/pull/29](https://github.com/k8snetworkplumbingwg/linuxptp-daemon/pull/29). 4.19   f87624ad393cc09cfd2d9d755b2d9a7758238501
- [https://github.com/k8snetworkplumbingwg/linuxptp-daemon/pull/18](https://github.com/k8snetworkplumbingwg/linuxptp-daemon/pull/18). 4.19 f87624ad393cc09cfd2d9d755b2d9a7758238501
- https://github.com/openshift/linuxptp-daemon/pull/374 4.19 e88d5f81aef061194843bfabd36dbc2c1bb53466

OCPBUGS-57037: 2-port Ordinary Clock backport from 4.19 to 4.18

---

Makefile
pkg/daemon/daemon.go
pkg/daemon/gpsd.go
pkg/daemon/gpspipe.go
pkg/daemon/gpspipe_test.go

Cherry pick form upstream PR https://github.com/k8snetworkplumbingwg/linuxptp-daemon/pull/58
and downstream 4.20 commit https://github.com/openshift/linuxptp-daemon/commit/dcd31fd57f0dcb5f2e922b2c52cb2ae7a969d6ce
This PR improves process management and error handling for the gpsd and gpspipe daemons by:
Adding proper process termination with timeouts (graceful SIGTERM, then SIGKILL if needed)
Improving restart logic and reducing tight restart loops
Enhancing named pipe (FIFO) creation with retries and better error messages
Problem
The gpspipe process was experiencing two critical issues:
Multiple processes running simultaneously: The restart logic in CmdRun() was creating new processes before properly checking if the previous process should be stopped, leading to multiple gpspipe …

OCPBUGS-58131: Fix gpspipe multiple process and named pipe creation issues[release-4.16]
