openshift/linuxptp-daemon

- pkg/daemon/metrics.go
This PR fix an issue with metric parsing
Issue:
ptp4l[76560.366]: rms   25 max   28 freq +16596 +/-   1
E0122 09:28:28.924420  231135 metrics.go:110] ptp4l failed to extract metrics unknown output format
Fix:
We check now the len to find if we have a deply from master or not.
phc2sys[80512.201]: enp6s0 rms   20 max   20 freq +16540 +/-   0 delay  1183 +/-   0
E0122 10:40:07.737644  160830 metrics.go:110] phc2sys failed to extract metrics unknown output format
Fix:
We now remove eveything before the "rms" string
> Fix metric parsing

- cmd/main.go
- pkg/daemon/daemon.go
This PR allow to apply a custom ptp4l.conf file
> Allow to use the ptp4lConf variable

- pkg/daemon/metrics.go
base on https://github.com/openshift/linuxptp-daemon/pull/15
This PR allow the linuxptp-daemon to expose both metric types
summary:
```
ptp4l[326.707]: rms   32 max   42 freq  -2614 +/-  15 delay  1488 +/-   0
phc2sys[326.903]: CLOCK_REALTIME rms   96 max   96 freq -84573 +/-   0 delay   427 +/-   0
```
regular:
```
ptp4l[242.706]: master offset        -19 s2 freq   -2446 path delay      1563
phc2sys[242.904]: CLOCK_REALTIME phc offset        19 s2 freq  -84406 delay    376
```
> Support no summary

- README.md
- cmd/main.go
- pkg/daemon/config.go
- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
This PR needs https://github.com/openshift/ptp-operator/pull/67 in the operator to support multiple profiles
Base on the proposal https://github.com/openshift/enhancements/pull/431
> Support multiple interfaces

- pkg/network/utils.go
This commit add the avility to discovery the n3000 network nics as ptp capable nics
> Add N3000 network nics discovery

- deploy/00-ns.yaml
Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>
> Bug 1974312: Remove unnecessary run-level value

- pkg/daemon/daemon.go
In a Boundary Clock configuration where multiple interfaces are
configured, it is not supported to include multiple interfaces in the
ptpconfig yaml.  Instead, these interfaces must be specified in the
ptpconfig config yaml.
When the interface is not directly specified in the ptpconfig yaml, it
is necessary to specify one or more interfaces in the ptpconfig config
yaml.
> Support handling empty interface

- pkg/daemon/daemon.go
Add support for handling PtpSchedulingPolicy and PtpSchedulingPriority,
which are used to configure SCHED_FIFO scheduling.
> Add support for changing ptp process scheduling

- pkg/daemon/metrics.go
Address the Bug, fixes renaming of offset metrics. Once the PR is merged, need to fix the alert rule in ptp-operator
This PR  fixes the renaming of metrics as per the source of the offset is reported in the log. As of now, we have three sources phc, system, and master offset. The metrics are reported as follows
Example logs
``` 
phc2sys[345276.663]: `master` offset       -265 s2 freq   -2265 path delay        87
phc2sys[345276.663]: [ptp4l.0.config] CLOCK_REALTIME `phc` offset         9 s2 freq  -78510 delay   1108
phc2sys[345276.663]: [ptp4l.0.config] ens5f0 `phc` offset         7 s2 freq   -2248 delay   2893
phc2sys[345276.663]: [ptp4l.0.config] ens5f2 `sys` offset         77 s2 freq   -2248 delay   2893
````
Renames …
> Bug 2019198:Rename Prometheus metrics

- pkg/daemon/daemon.go
If ptp4l or phc2sys processes die, they should be restarted by
linuxptp-daemon.
> Bug 2016185: Add restart for ptp4l and phc2sys

- pkg/daemon/daemon.go
Patch back of ptp4l and phc2sys restart to 4.9
> Bug 2034353: Add process restart 4.9

- pkg/daemon/daemon.go
Cleaning termination with an exit in defer function and not holding the lock for asynchronous calls like cmd start and sig term.
This was causing the listener at the sidecar to see multiple socket connections (2 per termination)
> Bug 2054351:Fix restart process  that was holding  lock on asynchronous call, avoid multiple socket error 

- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
Generate ptp4l/phc2sys process status  metrics  and report  status to sidecar when event  framework is  enabled
Adding health check metrics for the PTP4l process and Phc2sys process.
Generate metrics for process status and send ptp4l status and pch2sys status to event framework.
> Generate ptp4l/phc2sys process status metrics 

- go.mod
- go.sum
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
- vendor/modules.txt
prometheus/client_golang: Denial of service using InstrumentHandlerCounter
updated prometheus go-client to 1.11.1
> Bug 2067851: Denial of service using InstrumentHandlerCounter

- OWNERS
Signed-off-by: Nishant Parekh <nparekh@redhat.com>
> add Nishant Parekh to owners

- cmd/main.go
Work in progress!!
This is to add a nodeName label to the linux-ptp-daemon pods. The nodeName label indicates the node name where the pod is deployed. This allows for using nodename as a label selector in the ptp-event service. 
To support ptp events service in multinode, we propose to configure a service per node and to use the app name and nodeName labels as pod/app selectors. This PR is related to the following PR in the ptp-operator project: https://github.com/openshift/ptp-operator/pull/282
> Adding nodeName Label to linux-ptp-daemon pod to support multinode ptp events

- Dockerfile
- Dockerfile.rhel7
This reverts commit eae28ec331e8e9ad66571dfd434d022768e469f4.
> Revert "Add leap-seconds.list to Dockerfile"

- pkg/daemon/config.go
- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
/hold
still need more testing as well as vendoring in https://github.com/openshift/ptp-operator/pull/287 .  Pushing first draft for review.
> Add support for ts2phc in linuxptp-daemon

- pkg/daemon/metrics.go
> Add metrics to ts2phc

- cmd/main.go
- pkg/daemon/metrics.go
fix multi node http event support
and ts2phc metrics
> fix nodename for multinode service

- Dockerfile
> update go19 and 4.13 base image

- pkg/daemon/config.go
- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
> OCPBUGS-7829: Bug OCPBUGS-6088: Preserve iface ordering in ptpconfig

- cmd/main.go
Some clusters are slow to configure cluster access right for the pod. If the linuxptp-daemon pod fails to access pods in the cluster, fail the linux ptpdaemon pod to trigger a pod recreation and retry.
In case of slow cluster, and if not retrying, the clock fails to acquire sync complaining about ptp:
```
E0419 21:08:35.036983 3962510 daemon.go:443] error trying to connect to event socket
```
initial unauthorized error:
```
E0419 21:34:50.318916 4020630 main.go:164] Unauthorized
E0419 21:34:50.344475 4020630 ptpdev.go:43] failed to get NodePtpDevice CR for node master1: Unauthorized
```
> OCPBUGS-12730: Linuxptp failing to create pod node name label

- addons/generic/generic.go
- addons/intel/e810.go
- pkg/daemon/daemon.go
- pkg/daemon/plugin.go
- pkg/plugin/plugin.go
Changes to plugin structure also required to allow sharing data between OnPTPConfigChange and PopulateHwConfig, which is required to write the status to the nodeptpdevice
> Add ublx config to plugin

- cmd/main.go
- pkg/config/config.go
- pkg/daemon/daemon.go
This commit introduces periodical clock class checks to indicate when there is a change
/cc @aneeshkp @josephdrichard @jzding @nishant-parekh
> OCPBUGS-14681: fix clock class updates

- cmd/main.go
- pkg/config/config.go
- pkg/daemon/daemon.go
This commit introduces periodical clock class checks to indicate when there is a change
/cc @nishant-parekh @josephdrichard @jzding
> OCPBUGS-15413: [release-4.13] fix clock class updates

- pkg/daemon/daemon.go
> OCPBUGS-15479: Fixup ptp process starting

- cmd/main.go
- pkg/config/config.go
- pkg/daemon/daemon.go
This commit introduces periodical clock class checks to indicate when there is a change
> OCPBUGS-15429: [release-4.12] fix clock class updates

- addons/generic/generic.go
This logging will be used for testing plugin framework
> CNF-7017: Add generic plugin logging

- pkg/daemon/config.go
- pkg/daemon/daemon.go
GM = No Slave interface
BC = Multiple interfaces with atleast one slave
OC = Single slave interface
> compute clockType from ptp4lConfig

- Dockerfile
- Dockerfile.rhel7
also update builder from golang-1.19 to golang-1.20 in Dockerfile
> Bug OCPBUGS-15370: update Dockerfile.rhel7 with Dockerfile content

- pkg/daemon/daemon.go
- pkg/daemon/gpsd.go
- pkg/daemon/gpspipe.go
- pkg/dpll/dpll.go
- pkg/event/event.go
- pkg/ublox/ublox.go
Fixed bugs:
GM Metrics
GM Clock Type
> bug fix with metrics and logs

- pkg/config/config.go
- pkg/daemon/daemon.go
- pkg/daemon/gpsd.go
- pkg/daemon/gpspipe.go
- pkg/daemon/process.go
- pkg/dpll/dpll.go
- pkg/dpll/dpll_test.go
- pkg/event/event.go
This  PR fixes issue with hanging on exitChannel and not terminating all process
> Fix termination of process on ptpconfig delete

- pkg/daemon/gpsd.go
- pkg/dpll/dpll.go
- pkg/dpll/dpll_test.go
- pkg/event/event.go
- pkg/ublox/ublox.go
fixed sysfs reading content
Set gpsd debug level to default 0
added interface to teh log for dpll /gnss/gmstats and gpsd
> OCPBUGS-16188:Linuxptp-daemon crashing due to index out of range doing DPLL monitoring

- pkg/daemon/daemon.go
- pkg/dpll/dpll.go
- pkg/dpll/dpll_test.go
- pkg/event/event.go
- pkg/event/pubsub.go
When netlink or sysfs is not implemented, the pod crashes with nil pointer exception.
Added checks to support absence of  dpll
> OCPBUGS-17486: linuxptp-daemon-container stuck in CrashLoopBackOff upon deployment on GM config

- pkg/daemon/daemon.go
- pkg/dpll/dpll.go
- pkg/event/event.go
- pkg/protocol/type.go
clockclass run via go rountine
> Fixed crashloop and clock class thread hijacking by using channel 

- Dockerfile
> copy leap sec file to the right image

- pkg/dpll/dpll.go
> Fix mutex lock when locked

- pkg/dpll/dpll.go
this commit fixes several issues in holdover timer, units and logic
//cc @aneeshkp @jzding @josephdrichard @nishant-parekh 
Tested and looks good. One thing that still doesn't work - when in holdover, clock class in metrics is 248.
In locked and freerun clock class was correct
> fix holdover logic

- pkg/daemon/daemon.go
- pkg/daemon/gpspipe.go
- pkg/daemon/metrics.go
- pkg/dpll/dpll.go
- pkg/event/event.go
Fix the GM state incorrect   reported in metrics
> OCPBUGS-17765: ptp clock is not locked in GM configuration

- Makefile
- pkg/dpll/dpll_test.go
- pkg/event/event.go
- pkg/event/event_test.go
- pkg/event/stats.go
This PR adds unit tets to verify GM state
> Add unit test for linuxptp daemon

- pkg/ublox/ublox_test.go
> fix ublox tool testing 

- pkg/event/event.go
fix GM Status to print  every sec for GM configuration
> OCPBUGS-18903: T-GM-STATUS not logged every sec  when dpll and gnss events were not reported  

- pkg/daemon/gpsd.go
- pkg/dpll/dpll.go
- pkg/event/event.go
- pkg/event/pubsub.go
- pkg/event/pubsub_test.go
Handle register and unregister of monitoring lifecycle for dpll/gpsd
>     OCPBUGS-19345:  ptp clock does not stay locked in GM configuration when threshold is changed in ptpconfig

- pkg/event/event.go
- pkg/event/pubsub.go
```
Linux PTP daemon      | 4.13 (OC)  | 4.14(OC)     | 4-14-OC -  FIXED     |     4.14-GM - FIXED
----------------------------------------------------------------------------------------------------------------------------------
Cpu Core          | 9m           |16m              | 9m                        | 11m
Memory            | 20Mi         | 20Mi            | 15Mi                      | 34Mi
```
> OCPBUGS-19721: Linuxptp daemon overhead ~2x higher with 4.14 operator

- pkg/dpll-netlink/dpll-uapi.go
- pkg/dpll-netlink/dpll.go
@aneeshkp this is an attempt for manual dpll structure update.
If it doesn't work, will need to try and regenerate the files.
> OCPBUGS-22278:  Dpll update in RHEL 9.2 will not generate any DPLL events

- pkg/daemon/config.go
- pkg/daemon/daemon.go
- pkg/daemon/gpsd.go
- pkg/daemon/metrics.go
- pkg/dpll/dpll.go
- pkg/event/event.go
- pkg/event/event_test.go
- pkg/pmc/pmc.go
When NMEA string is lost but GPS is in sync ,set ts2phc to free run
> OCPBUGS-20514: PTP HW Clock Class after disabling NMEA sentences set to FREERUN

- pkg/daemon/metrics.go
OCPBUGS-20420  : [master]concurrent map reading master offset map in linuxptpdaemon
Signed-off-by: Aneesh Puttur <aputtur@redhat.com>
> [release-4.14] OCPBUGS-20495: concurrent map reading master offset map in linuxptpdaemon

- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
- pkg/event/event.go
- pkg/event/event_test.go
- pkg/event/stats.go
- pkg/event/stats_test.go
This  code adds  updates  from 1 card GM  to support for multi Card GM
> dual ts2phc /dpll support for multi  card T-GM

- pkg/event/event.go
fix master metrics for ts2phc with interface index masked
> Fix master metrics interface names

- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
- pkg/dpll/dpll_test.go
- pkg/event/event.go
- pkg/event/event_test.go
Add nmea_status and clock class metrics
> [release 4.14]  OCPBUGS-23982: nmea_status and clock_class metrics missing in 4.14 linuxptpdaemon

- pkg/event/event.go
Ignore unknown interface for GM state and wait until interface is available
> OCPBUGS-25682: False GM process with unknown interface appears after node reboot

- extra/leap-seconds.list
> OCPBUGS-25939: T-GM ts2phc IERS Bulletin expired December the 28thupdate leap file to june 2024

- go.mod
- go.sum
- vendor/github.com/jaypipes/ghw/README.md
- vendor/github.com/jaypipes/ghw/doc.go
- vendor/github.com/jaypipes/ghw/pkg/block/block.go
- vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go
- vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go
- vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go
- vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go
- vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go
- vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go
- vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
- vendor/github.com/jaypipes/ghw/pkg/net/net.go
- vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go
- vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go
- vendor/github.com/jaypipes/ghw/pkg/util/util.go
- vendor/modules.txt
- updated ghw version from 0.9.0 => 0.12.0
- https://app.snyk.io/org/openshift-ci-internal/project/a017c91c-5061-483d-b4c0-fe4d8701870c#issue-8931dfa1-44c4-435f-aee1-f42059d58c99
- https://app.snyk.io/org/openshift-ci-internal/project/a017c91c-5061-483d-b4c0-fe4d8701870c#issue-60f09319-176f-49ae-a320-926f188d004f
- https://app.snyk.io/org/openshift-ci-internal/project/a017c91c-5061-483d-b4c0-fe4d8701870c#issue-b6193a25-8004-492b-a29d-4e5ccdda513f
> CWE fixes for linuxptp-daemon

- addons/intel/README.md
Document an example of configuring phase offset pin filter in the example config
/cc @aneeshkp @josephdrichard
> CNF-11612: Add phase offset pin filter doc

- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
- pkg/daemon/metrics.go
`HELP openshift_ptp_ha_profile_status 0 = INACTIVE 1 = ACTIVE 0 # 
TYPE openshift_ptp_ha_profile_status gauge
openshift_ptp_ha_profile_status{node="node1",process="phc2sys",profile="profile1"} 1
openshift_ptp_ha_profile_status{node="node1",process="phc2sys",profile="profile2"} 0`
> Add HA metrics to PTP HA 

- pkg/daemon/daemon.go
update message tag to actual config file so HA profile can be read from the config
> PTPHA: update message tag to actual config file 

- pkg/daemon/daemon.go
logging all  inactive profile  for ha
> Fix ha profile to log all profiles 

- pkg/daemon/daemon.go
- pkg/daemon/gpsd.go
- pkg/daemon/gpspipe.go
- pkg/dpll/dpll.go
- pkg/dpll/dpll_test.go
- pkg/event/event.go
- pkg/event/pubsub.go
- pkg/event/stats.go
cherry-pick form 
https://github.com/openshift/linuxptp-daemon/pull/298
OCPBUGS-31706: ubxtool cold boot has no effect on logs and metrics
>  [release-4.15]  OCPBUGS-32140: ubxtool cold boot has no effect on logs and metrics

- addons/intel/e810.go
- go.mod
- go.sum
- pkg/daemon/config.go
- pkg/daemon/daemon.go
- pkg/daemon/daemon_internal_test.go
- pkg/daemon/testdata/synce-profile-bad-order.yaml
- pkg/daemon/testdata/synce-profile-custom-id.yaml
- pkg/daemon/testdata/synce-profile-dual.yaml
- pkg/daemon/testdata/synce-profile-no-ifaces.yaml
- pkg/daemon/testdata/synce-profile.yaml
- vendor/github.com/bigkevmcd/go-configparser/LICENSE
- vendor/github.com/bigkevmcd/go-configparser/README.md
- vendor/github.com/bigkevmcd/go-configparser/TODO.md
- vendor/github.com/bigkevmcd/go-configparser/chainmap/chainmap.go
- vendor/github.com/bigkevmcd/go-configparser/configparser.go
- vendor/github.com/bigkevmcd/go-configparser/interpolation.go
- vendor/github.com/bigkevmcd/go-configparser/methods.go
- vendor/github.com/bigkevmcd/go-configparser/options.go
- vendor/github.com/bigkevmcd/go-configparser/section.go
- vendor/modules.txt
This commit adds automatic assignment of clock IDs to syncE devices.
> assign clock IDs to SyncE devices

- pkg/daemon/daemon.go
- pkg/daemon/gpsd.go
- pkg/ublox/ublox.go
This is a manual cherrypick of #326 
/cc @aneeshkp @josephdrichard @jzding @nishant-parekh
> [release-4.15] OCPBUGS-36842: Fix ublox cpu spike

- pkg/daemon/daemon.go
- pkg/daemon/gpsd.go
- pkg/ublox/ublox.go
This PR fixed ublox CPU spiking due to not gracefully shutdown of ublox 
This is cherry pick of https://github.com/openshift/linuxptp-daemon/pull/331
> [release-4.14] OCPBUGS-37204: Fix ublox cpu spike

- addons/intel/e810.go
- pkg/daemon/daemon_internal_test.go
- pkg/daemon/metrics.go
- pkg/daemon/testdata/synce-follower-profile.yaml
- pkg/synce/synce.go
ifxed bug that was preventing adding of Clock id  to synce config
> fix clockid adding to synce device

- pkg/event/event.go
This commit fixes grandmaster announce flags to be consistent with ITU-T 8275.1
>  OCPBUGS-37646: fix grandmaster settings

- hack/build.sh
Fix fips complaint issue to enable fips support
> OCPBUGS-47754: [release-4.17] Fix fips complaint issue to enable fips support

- hack/build.sh
Fix fips complaint issue to enable fips support
> OCPBUGS-47756: [release-4.15] Fix fips complaint issue to enable fips support

- hack/build.sh
Fix fips complaint issue to enable fips support
> [release-4.14] OCPBUGS-47757: Fix fips complaint issue to enable fips support

- pkg/daemon/daemon.go
- pkg/debug/debug.go
- pkg/debug/debug_test.go
- pkg/dpll/dpll.go
- pkg/dpll/dpll_test.go
- pkg/event/event.go
- pkg/event/event_test.go
This is a missing port from https://github.com/openshift/linuxptp-daemon/pull/379
Remove clock class 140, add debug package and prints
/cc @aneeshkp @josephdrichard @jzding
> OCPBUGS-51187: [4.17] Port 4.14 changes

- pkg/daemon/daemon.go
- pkg/debug/debug.go
- pkg/debug/debug_test.go
- pkg/dpll/dpll.go
- pkg/dpll/dpll_test.go
- pkg/event/event.go
- pkg/event/event_test.go
This is a missing port from #379 
Remove clock class 140, add debug package and prints
/cc @aneeshkp @josephdrichard @jzding
> OCPBUGS-51115: [4.16]Port 4.14 changes

- pkg/daemon/daemon.go
Reverts openshift/linuxptp-daemon#418
> [Release-4.16] OCPBUGS-55119: Revert Add delay in linuxptp-daemon to wait for socket to be read

- pkg/event/event.go
Also, Fix updateCLockClass name
> OCPBUGS-55487: [release-4.15] OCPBUGS-55171: Set pmc for TimeTraceable change

- pkg/event/event.go
This is a manual cherry-pick of #351 
This commit fixes grandmaster announce flags to be consistent with ITU-T 8275.1
/cc @aneeshkp @jzding @josephdrichard @nocturnalastro
> OCPBUGS-55740: [release-4.17] fix grandmaster settings

- pkg/event/event.go
Reverts openshift/linuxptp-daemon#437
> Revert "OCPBUGS-55740: [release-4.17] fix grandmaster settings"

- pkg/dpll/dpll.go
- pkg/dpll/dpll_test.go
Manual cherrypick of #428 
Simplify DPLL eventing logic by decoupling holdover and LHAQ states Remove "locked" DPLL state handling, keeping in Holdover until the LHAQ state reached.
Fix a race condition in tests where event source was not fast enough to be set before the event proces
/assign @aneeshkp
> OCPBUGS-55466: [release-4.15] keep in holdover until locked-holdover-acquired

- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
- pkg/event/event.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
> [release-4.16] OCPBUGS-57479: Fix interface name for summary metrics
